<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class ServiceSeeder extends Seeder
{
    public function run()
    {
        DB::table('services')->insert([
            [
                'title' => 'AC রিপেয়ার',
                'slug' => 'ac-repair',
                'description' => 'পেশাদার AC রিপেয়ার সার্ভিস। ফ্রিজ গ্যাস লিক, কম্প্রেসার সমস্যা, ফ্যান মোটর নষ্ট সহ সব ধরনের এসি মেরামত সেবা।',
                'icon' => 'fas fa-wrench',
                'image' => 'front/images/services/ac-repair.jpg',
                'benefits' => json_encode([
                    ['title' => 'অভিজ্ঞ টেকনিশিয়ান', 'description' => '১০+ বছর অভিজ্ঞ টেকনিশিয়ান দ্বারা সার্ভিস'],
                    ['title' => 'ওয়ারেন্টি', 'description' => 'সকল সার্ভিসে ওয়ারেন্টি প্রদান'],
                    ['title' => 'দ্রুত সেবা', 'description' => 'কল পাওয়ার ৩০ মিনিটের মধ্যে সার্ভিস'],
                    ['title' => 'সাশ্রয়ী মূল্য', 'description' => 'গুণগত মান বজায় রেখে সাশ্রয়ী মূল্যে সার্ভিস'],
                    ['title' => 'অরিজিনাল পার্টস', 'description' => 'অরিজিনাল এবং কোয়ালিটি পার্টস ব্যবহার'],
                    ['title' => 'ফ্রি ইনস্পেকশন', 'description' => 'মেরামতের আগে ফ্রি চেকআপ'],
                ]),
                'process' => json_encode([
                    ['title' => 'কল করুন', 'description' => 'আমাদের হটলাইনে কল করে অ্যাপয়েন্টমেন্ট নিন'],
                    ['title' => 'চেকআপ', 'description' => 'আমাদের টেকনিশিয়ান ফ্রি চেকআপ করবেন'],
                    ['title' => 'মেরামত', 'description' => 'প্রয়োজনীয় মেরামত সম্পন্ন করা হয়'],
                    ['title' => 'টেস্টিং', 'description' => 'সার্ভিস শেষে সম্পূর্ণ টেস্টিং করা হয়'],
                ]),
                'meta_title' => 'AC Repair Service in Mirpur | Best AC Repair in Dhaka',
                'meta_description' => 'Best AC repair service in Mirpur, Dhaka. Professional AC repair, gas refill, compressor fix at affordable prices.',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'AC সার্ভিসিং',
                'slug' => 'ac-servicing',
                'description' => 'সম্পূর্ণ AC সার্ভিসিং প্যাকেজ। ডিপ ক্লিনিং, ফিল্টার ওয়াশ, গ্যাস চেক, কয়েল ক্লিনিং সহ নিয়মিত সার্ভিসিং।',
                'icon' => 'fas fa-snowflake',
                'image' => 'front/images/services/ac-servicing.jpg',
                'benefits' => json_encode([
                    ['title' => 'ডিপ ক্লিনিং', 'description' => 'ইনডোর ও আউটডোর ইউনিটের ডিপ ক্লিনিং'],
                    ['title' => 'গ্যাস চেক', 'description' => 'গ্যাস প্রেসার ও লিক চেক'],
                    ['title' => 'ফিল্টার ক্লিন', 'description' => 'এয়ার ফিল্টার পরিষ্কার'],
                    ['title' => 'কয়েল ক্লিনিং', 'description' => 'কনডেন্সার ও ইভাপোরেটর কয়েল ক্লিনিং'],
                    ['title' => 'ড্রেন চেক', 'description' => 'ড্রেন লাইন চেক ও পরিষ্কার'],
                    ['title' => 'পারফরম্যান্স টেস্ট', 'description' => 'সম্পূর্ণ পারফরম্যান্স টেস্ট'],
                ]),
                'process' => json_encode([
                    ['title' => 'বুকিং', 'description' => 'ফোন বা WhatsApp এ বুকিং দিন'],
                    ['title' => 'ইনস্পেকশন', 'description' => 'টেকনিশিয়ান দ্বারা সম্পূর্ণ চেকআপ'],
                    ['title' => 'সার্ভিসিং', 'description' => 'সম্পূর্ণ সার্ভিসিং সম্পন্ন'],
                    ['title' => 'ডেলিভারি', 'description' => 'সার্ভিস সম্পন্ন后 কাস্টমার ডেলিভারি'],
                ]),
                'meta_title' => 'AC Servicing in Mirpur | AC Deep Cleaning Service Dhaka',
                'meta_description' => 'Professional AC servicing in Mirpur. Deep cleaning, gas check, filter wash at best price in Dhaka.',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'AC ইনস্টলেশন',
                'slug' => 'ac-installation',
                'description' => 'নতুন AC ইনস্টলেশন সার্ভিস। ওয়াল মাউন্ট, ডাক্টিং, পাইপিং সহ সম্পূর্ণ ইনস্টলেশন সেবা।',
                'icon' => 'fas fa-tools',
                'image' => 'front/images/services/ac-installation.jpg',
                'benefits' => json_encode([
                    ['title' => 'প্রফেশনাল ইনস্টলেশন', 'description' => 'অভিজ্ঞ টিম দ্বারা ইনস্টলেশন'],
                    ['title' => 'কোয়ালিটি ম্যাটেরিয়াল', 'description' => 'প্রিমিয়াম মানের পাইপ ও ফিটিংস'],
                    ['title' => 'ওয়ারেন্টি', 'description' => 'ইনস্টলেশন ওয়ারেন্টি প্রদান'],
                    ['title' => 'ফ্রি ডেলিভারি', 'description' => 'ঢাকা শহরে ফ্রি ডেলিভারি'],
                    ['title' => 'সেফটি চেক', 'description' => 'সম্পূর্ণ সেফটি চেকআপ'],
                    ['title' => 'ডেমো', 'description' => 'ব্যবহারের নিয়ম দেখানো হয়'],
                ]),
                'process' => json_encode([
                    ['title' => 'সাইট ভিজিট', 'description' => 'ফ্রি সাইট ভিজিট ও পরিমাপ'],
                    ['title' => 'ইনস্টলেশন', 'description' => 'পেশাদারভাবে ইনস্টলেশন সম্পন্ন'],
                    ['title' => 'টেস্টিং', 'description' => 'সম্পূর্ণ টেস্টিং ও চেকিং'],
                    ['title' => 'হ্যান্ডওভার', 'description' => 'কাস্টমারকে বুঝিয়ে দেওয়া'],
                ]),
                'meta_title' => 'AC Installation Service in Mirpur | AC Installer Dhaka',
                'meta_description' => 'Expert AC installation service in Mirpur. Professional installation with warranty at affordable price.',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'AC গ্যাস রিফিল',
                'slug' => 'ac-gas-refill',
                'description' => 'AC গ্যাস রিফিল ও লিক রিপেয়ার। R22, R32, R410A সহ সব ধরনের গ্যাস রিফিল সার্ভিস।',
                'icon' => 'fas fa-fire',
                'image' => 'front/images/services/ac-gas-refill.jpg',
                'benefits' => json_encode([
                    ['title' => 'গ্যাস লিক ডিটেক্ট', 'description' => 'আধুনিক মেশিন দ্বারা লিক ডিটেক্ট'],
                    ['title' => 'অরিজিনাল গ্যাস', 'description' => '১০০% অরিজিনাল রেফ্রিজারেন্ট গ্যাস'],
                    ['title' => 'প্রেসার টেস্ট', 'description' => 'গ্যাস প্রেসার সঠিকভাবে টেস্টিং'],
                    ['title' => 'লিক রিপেয়ার', 'description' => 'গ্যাস লিক সম্পূর্ণ রিপেয়ার'],
                    ['title' => 'ওয়ারেন্টি', 'description' => '৩ মাস ওয়ারেন্টি'],
                    ['title' => 'সাশ্রয়ী মূল্য', 'description' => 'সর্বনিম্ন মূল্যে গ্যাস রিফিল'],
                ]),
                'process' => json_encode([
                    ['title' => 'ডায়াগনোসিস', 'description' => 'গ্যাস লিক ও প্রেসার চেক'],
                    ['title' => 'লিক রিপেয়ার', 'description' => 'প্রয়োজনে লিক রিপেয়ার'],
                    ['title' => 'গ্যাস রিফিল', 'description' => 'সঠিক প্রেসারে গ্যাস রিফিল'],
                    ['title' => 'টেস্টিং', 'description' => 'কুলিং টেস্ট ও চেকআপ'],
                ]),
                'meta_title' => 'AC Gas Refill in Mirpur | AC Gas Leak Repair Dhaka',
                'meta_description' => 'AC gas refill and leak repair service in Mirpur. R22, R32, R410A gas refill at best price.',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ওয়াশিং মেশিন রিপেয়ার',
                'slug' => 'washing-machine',
                'description' => 'সব ধরনের ওয়াশিং মেশিন মেরামত। অটোমেটিক ও সেমি-অটোমেটিক ওয়াশিং মেশিন রিপেয়ার সার্ভিস।',
                'icon' => 'fas fa-tshirt',
                'image' => 'front/images/services/washing-machine.jpg',
                'benefits' => json_encode([
                    ['title' => 'সব ব্র্যান্ড', 'description' => 'সব ব্র্যান্ডের ওয়াশিং মেশিন সার্ভিস'],
                    ['title' => 'অটোমেটিক এক্সপার্ট', 'description' => 'ফ্রন্ট ও টপ লোড এক্সপার্ট'],
                    ['title' => 'মোটর রিপেয়ার', 'description' => 'মোটর ও পিসিবি রিপেয়ার'],
                    ['title' => 'ড্রেন সমস্যা', 'description' => 'ড্রেন পাম্প ও হোস সমস্যা সমাধান'],
                    ['title' => 'স্পিনিং সমস্যা', 'description' => 'স্পিনিং ও ভারসাম্য সমস্যা সমাধান'],
                    ['title' => 'ওয়ারেন্টি', 'description' => 'সার্ভিস ওয়ারেন্টি'],
                ]),
                'process' => json_encode([
                    ['title' => 'কল/মেসেজ', 'description' => 'যোগাযোগ করে সমস্যা জানান'],
                    ['title' => 'ভিজিট', 'description' => 'টেকনিশিয়ান ভিজিট'],
                    ['title' => 'মেরামত', 'description' => 'প্রয়োজনীয় মেরামত'],
                    ['title' => 'টেস্টিং', 'description' => 'সম্পূর্ণ টেস্টিং'],
                ]),
                'meta_title' => 'Washing Machine Repair in Mirpur | Washing Machine Service Dhaka',
                'meta_description' => 'Professional washing machine repair service in Mirpur. Automatic and semi-automatic washing machine repair.',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ফ্রিজ রিপেয়ার',
                'slug' => 'refrigerator',
                'description' => 'সব ধরনের ফ্রিজ ও রেফ্রিজারেটর মেরামত। নো ফ্রস্ট, ডায়রেক্ট কুল, ওয়াইন কুলার সহ সব ধরনের সার্ভিস।',
                'icon' => 'fas fa-thermometer-half',
                'image' => 'front/images/services/refrigerator.jpg',
                'benefits' => json_encode([
                    ['title' => 'সব ব্র্যান্ড', 'description' => 'সব ব্র্যান্ডের ফ্রিজ সার্ভিস'],
                    ['title' => 'কম্প্রেসার এক্সপার্ট', 'description' => 'কম্প্রেসার রিপেয়ার ও রিপ্লেস'],
                    ['title' => 'গ্যাস চার্জিং', 'description' => 'ফ্রিজ গ্যাস চার্জিং'],
                    ['title' => 'থার্মোস্ট্যাট', 'description' => 'থার্মোস্ট্যাট ও সেন্সর রিপেয়ার'],
                    ['title' => 'ডিফ্রস্ট সমস্যা', 'description' => 'ডিফ্রস্ট ও টাইমার সমস্যা সমাধান'],
                    ['title' => 'ওয়ারেন্টি', 'description' => 'সার্ভিস ওয়ারেন্টি'],
                ]),
                'process' => json_encode([
                    ['title' => 'ডায়াগনোসিস', 'description' => 'সম্পূর্ণ সমস্যা নির্ণয়'],
                    ['title' => 'কোট', 'description' => 'মেরামতের খরচ জানানো'],
                    ['title' => 'রিপেয়ার', 'description' => 'মেরামত সম্পন্ন'],
                    ['title' => 'টেস্টিং', 'description' => 'কুলিং টেস্ট'],
                ]),
                'meta_title' => 'Fridge Repair in Mirpur | Refrigerator Service Dhaka',
                'meta_description' => 'Expert refrigerator repair service in Mirpur. No frost, direct cool fridge repair at affordable price.',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'মাইক্রোওয়েভ রিপেয়ার',
                'slug' => 'microwave',
                'description' => 'সব ধরনের মাইক্রোওয়েভ ওভেন মেরামত। ম্যাগনেট্রন, ট্রান্সফরমার, কন্ট্রোল প্যানেল রিপেয়ার।',
                'icon' => 'fas fa-microchip',
                'image' => 'front/images/services/microwave.jpg',
                'benefits' => json_encode([
                    ['title' => 'সব ব্র্যান্ড', 'description' => 'LG, Samsung, Panasonic সহ সব ব্র্যান্ড'],
                    ['title' => 'ম্যাগনেট্রন', 'description' => 'ম্যাগনেট্রন রিপেয়ার ও রিপ্লেস'],
                    ['title' => 'পিসিবি রিপেয়ার', 'description' => 'কন্ট্রোল প্যানেল ও পিসিবি রিপেয়ার'],
                    ['title' => 'ট্রান্সফরমার', 'description' => 'হাই ভোল্টেজ ট্রান্সফরমার রিপেয়ার'],
                    ['title' => 'টার্নটেবল', 'description' => 'টার্নটেবল মোটর রিপেয়ার'],
                    ['title' => 'ওয়ারেন্টি', 'description' => 'পার্টস ওয়ারেন্টি'],
                ]),
                'process' => json_encode([
                    ['title' => 'চেকআপ', 'description' => 'সম্পূর্ণ চেকআপ'],
                    ['title' => 'ডায়াগনোসিস', 'description' => 'সমস্যা নির্ণয়'],
                    ['title' => 'মেরামত', 'description' => 'প্রয়োজনীয় মেরামত'],
                    ['title' => 'টেস্টিং', 'description' => 'হিটিং টেস্ট'],
                ]),
                'meta_title' => 'Microwave Oven Repair in Mirpur | Microwave Service Dhaka',
                'meta_description' => 'Microwave oven repair service in Mirpur. Magnetron, transformer, control panel repair at best price.',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ডিশওয়াশার রিপেয়ার',
                'slug' => 'dishwasher',
                'description' => 'সব ধরনের ডিশওয়াশার মেশিন মেরামত। পাম্প, হিটার, কন্ট্রোল বোর্ড ও ড্রেন সমস্যা সমাধান।',
                'icon' => 'fas fa-utensils',
                'image' => 'front/images/services/dishwasher.jpg',
                'benefits' => json_encode([
                    ['title' => 'সব ব্র্যান্ড', 'description' => 'সব ব্র্যান্ডের ডিশওয়াশার সার্ভিস'],
                    ['title' => 'পাম্প রিপেয়ার', 'description' => 'ওয়াটার পাম্প ও ড্রেন পাম্প'],
                    ['title' => 'হিটার রিপেয়ার', 'description' => 'হিটার ও থার্মোস্ট্যাট'],
                    ['title' => 'পিসিবি এক্সপার্ট', 'description' => 'কন্ট্রোল বোর্ড রিপেয়ার'],
                    ['title' => 'লিক ফিক্স', 'description' => 'ওয়াটার লিক সমস্যা সমাধান'],
                    ['title' => 'ওয়ারেন্টি', 'description' => 'সার্ভিস ওয়ারেন্টি'],
                ]),
                'process' => json_encode([
                    ['title' => 'ইনস্পেকশন', 'description' => 'প্রবলেম ডায়াগনোসিস'],
                    ['title' => 'এস্টিমেট', 'description' => 'কস্ট এস্টিমেট'],
                    ['title' => 'রিপেয়ার', 'description' => 'মেরামত সম্পন্ন'],
                    ['title' => 'টেস্ট', 'description' => 'ওয়াশিং টেস্ট'],
                ]),
                'meta_title' => 'Dishwasher Repair in Mirpur | Dishwasher Service Dhaka',
                'meta_description' => 'Dishwasher repair service in Mirpur. Pump, heater, control board repair at affordable price in Dhaka.',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'গিজার রিপেয়ার',
                'slug' => 'geyser',
                'description' => 'ইলেকট্রিক ও গ্যাস গিজার মেরামত। হিটার এলিমেন্ট, থার্মোস্ট্যাট, ভার্ভ রিপেয়ার ও ইনস্টলেশন।',
                'icon' => 'fas fa-shower',
                'image' => 'front/images/services/geyser.jpg',
                'benefits' => json_encode([
                    ['title' => 'সব টাইপ', 'description' => 'ইলেকট্রিক ও গ্যাস গিজার সার্ভিস'],
                    ['title' => 'হিটার এলিমেন্ট', 'description' => 'হিটার এলিমেন্ট রিপেয়ার'],
                    ['title' => 'থার্মোস্ট্যাট', 'description' => 'থার্মোস্ট্যাট রিপ্লেস'],
                    ['title' => 'ইনস্টলেশন', 'description' => 'নতুন গিজার ইনস্টলেশন'],
                    ['title' => 'লিক রিপেয়ার', 'description' => 'ওয়াটার লিক রিপেয়ার'],
                    ['title' => 'ওয়ারেন্টি', 'description' => 'সার্ভিস ওয়ারেন্টি'],
                ]),
                'process' => json_encode([
                    ['title' => 'ভিজিট', 'description' => 'সাইট ভিজিট'],
                    ['title' => 'চেক', 'description' => 'সম্পূর্ণ চেকআপ'],
                    ['title' => 'মেরামত', 'description' => 'মেরামত সম্পন্ন'],
                    ['title' => 'টেস্টিং', 'description' => 'হিটার টেস্টিং'],
                ]),
                'meta_title' => 'Geyser Repair in Mirpur | Water Heater Service Dhaka',
                'meta_description' => 'Geyser and water heater repair service in Mirpur. Element, thermostat repair and installation.',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'হোম অ্যাপ্লায়েন্স সার্ভিস',
                'slug' => 'home-appliance',
                'description' => 'সব ধরনের হোম অ্যাপ্লায়েন্স মেরামত ও সার্ভিস। ইলেকট্রিক ও ইলেকট্রনিক পণ্য মেরামত করা হয়।',
                'icon' => 'fas fa-plug',
                'image' => 'front/images/services/home-appliance.jpg',
                'benefits' => json_encode([
                    ['title' => 'সব ডিভাইস', 'description' => 'সব ধরনের হোম অ্যাপ্লায়েন্স সার্ভিস'],
                    ['title' => 'ইলেকট্রিক এক্সপার্ট', 'description' => 'ইলেকট্রিক ও ইলেকট্রনিক এক্সপার্ট'],
                    ['title' => 'ওয়্যারিং', 'description' => 'ইলেকট্রিক ওয়্যারিং সমাধান'],
                    ['title' => 'সেফটি চেক', 'description' => 'ইলেকট্রিক সেফটি চেকআপ'],
                    ['title' => 'সাশ্রয়ী', 'description' => 'সাশ্রয়ী মূল্যে সার্ভিস'],
                    ['title' => 'ওয়ারেন্টি', 'description' => 'সার্ভিস ওয়ারেন্টি'],
                ]),
                'process' => json_encode([
                    ['title' => 'কল', 'description' => 'যোগাযোগ করুন'],
                    ['title' => 'ডায়াগনোসিস', 'description' => 'সমস্যা নির্ণয়'],
                    ['title' => 'সার্ভিস', 'description' => 'মেরামত সম্পন্ন'],
                    ['title' => 'টেস্টিং', 'description' => 'পারফরম্যান্স টেস্ট'],
                ]),
                'meta_title' => 'Home Appliance Repair in Mirpur | Appliance Service Dhaka',
                'meta_description' => 'All home appliance repair service in Mirpur. Electrical and electronic appliance repair at best price.',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
